version: 2.1
jobs:
  build:
    docker:
      - image: node:11.10.1
      #- image: circleci/node:12.18

    working_directory: ~/TTB

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn react-native-asset
      - run: yarn add @segment/analytics-react-native/src/bridge.ts:89:8

      - run: yarn react-native link
      #- run: yarn add @segment/analytics-react-native-firebase
      #- run: yarn add @react-native-firebase/app

      # run tests!
      - run: yarn test

      #- run: yarn build
      #- run: yarn react-native start

      - run: yarn react-native run-android --variant=DevDebug

      #- run: yarn netlify:deploy