version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
  react-native: react-native-community/react-native@4.4.2
jobs:
  build:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - firebase-deploy/deploy:
          token: $FIREBASE_DEPLOY_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

      # run tests!
      #- run: yarn run test:unit 

  #deploy-job:
  #     working_directory: ~/TTB 
   #    steps:
    #     - restore_cache:
     #        keys:
      #        - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
       #  - run:
        #     name: show directory 
         #    command: pwd
         #- run:
           #  name: Install Firebase
            # command: npm install --save-dev firebase-tools
         #- run:
          #   name: look in directory
           #  command: ls -ltr
         #- run:
          #   name: Deploy main to Firebase
           #  command: npm run firebase deploy -- --token=$FIREBASE_DEPLOY_TOKEN    


