version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0

  jobs:
    node:
      working_directory: ~/TTB
      docker:
        - image: cimg/node:15.7.0
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      
      - run:
          name: jest tests
          command: |
            yarn run test

      
  deploy-job:
       docker:
         - image: cimg/node:15.7.0
       working_directory: ~/TTB
       steps:
         - restore_cache:
             keys:
              - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
         - run:
             name: show directory 
             command: pwd
         - run:
             name: Install Firebase
             command: npm install --save-dev firebase-tools
         - run:
             name: look in directory
             command: ls -ltr
         - run:
             name: Deploy Master to Firebase
             command: npm run firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN    

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main
            