require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TTB' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for TTB
  pod 'Firebase/Analytics'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'TTBTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TTB-tvOS' do
  # Pods for TTB-tvOS

  target 'TTB-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
